Add extra checks for Ximera reqs

diff --git a/bin/ec-mon-add b/bin/ec-mon-add
--- a/bin/ec-mon-add
+++ b/bin/ec-mon-add
@@ -6,7 +6,7 @@ function fatal() {
 }
 
 function usage() {
-        echo "Not enough args, use $0 monip=<monip> monname=<monname> [ option=value ... ]" 1>&2
+        echo "Usage: $0 monip=<monip> monname=<monname> [ option=value ... ]" 1>&2
         echo "  Mandatory parameters:" 1>&2
         echo "          monip=<address>[:port] (first monitor IP address and optionally port)" 1>&2
         echo "          monname=string (first monitor name, default is \"prima\")" 1>&2
@@ -20,10 +20,12 @@ if [ "$1" = "" -o "$1" = "help" -o "$1" = "--help" -o "$1" = "-?" ] ; then
 fi
 
 cluster="ceph"
+system_wide_cluster="ceph"
 if [ -f /etc/sysconfig/ceph ] ; then
         . /etc/sysconfig/ceph
         if [ "$CLUSTER" != "" ] ; then
                 cluster="$CLUSTER"
+                system_wide_cluster="$CLUSTER"
         fi
 fi
 
@@ -35,6 +37,10 @@ while [ "$1" != "" ] ; do
     export "$param"="$value"
     shift
 done
+
+if [ "$cluster" != "$system_wide_cluster" -a ! -f /usr/lib/systemd/system/ximera-ceph-mon@.service ] ; then
+        fatal "Non-default cluster name requires Ximera units installed. Aborted"
+fi
 
 if [ "$monip" = "" -o "$monname" = "" ] ; then
 	echo "-- Mandatory parameters not set --" 1>&2
